# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Amalgam8
email: admin@amalgam8.io
description: > # this means to ignore newlines until "baseurl:"
  Amalgam8 is an open-source multi-tenant integration framework for polyglot microservices.
  It takes the tedium out of microservice integration, enabling faster development, and provides a centralized control plane to enable various DevOps functions such as red/black deployments, multi-version routing, resilience testing, etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amalgam8.io" # the base hostname & protocol for your site
github_username:  amalgam8

# Build settings
markdown: kramdown
